from datetime import date

MOCK_AUTHORS = [
    {
        "email": "priya.sharma@gmail.com",
        "name": "Priya Sharma",
        "book_title": "Echoes of the Yamuna",
        "final_submission_date": "2024-11-15",
        "book_live_date": "2025-01-10",
        "royalty_status": "Paid – ₹12,400 on 2025-03-31",
        "isbn": "978-93-5741-201-4",
        "add_on_services": ["Bestseller Package", "Editorial Review"],
        "whatsapp": "+91 9876543210",
        "instagram": "@priyawrites",
        "dashboard_name": "Priya S.",
    },
    {
        "email": "arjun.mehta@hotmail.com",
        "name": "Arjun Mehta",
        "book_title": "The Silent Monsoon",
        "final_submission_date": "2024-12-01",
        "book_live_date": "2025-02-14",
        "royalty_status": "Processing – Expected 2025-06-30",
        "isbn": "978-93-5741-202-1",
        "add_on_services": ["PR Campaign", "Author Copy x5"],
        "whatsapp": "+91 9123456789",
        "instagram": "@arjunmreads",
        "dashboard_name": "Arjun Mehta",
    },
    {
        "email": "kavitha.nair@yahoo.com",
        "name": "Kavitha Nair",
        "book_title": "Coconut Trees and Couplets",
        "final_submission_date": "2024-10-20",
        "book_live_date": "2024-12-05",
        "royalty_status": "Paid – ₹8,750 on 2025-01-31",
        "isbn": "978-93-5741-203-8",
        "add_on_services": ["Award Submission", "Bestseller Package"],
        "whatsapp": "+91 9988776655",
        "instagram": "@kavithanairpoetry",
        "dashboard_name": "Kavitha N.",
    },
    {
        "email": "rohit.desai@outlook.com",
        "name": "Rohit Desai",
        "book_title": "Mumbai Noir: Three Stories",
        "final_submission_date": "2025-01-08",
        "book_live_date": "2025-03-01",
        "royalty_status": "Not Yet Due – Book live < 90 days",
        "isbn": "978-93-5741-204-5",
        "add_on_services": ["Editorial Review"],
        "whatsapp": "+91 9876012345",
        "instagram": "@rohitdesaiwrites",
        "dashboard_name": "R. Desai",
    },
    {
        "email": "sunita.agarwal@rediffmail.com",
        "name": "Sunita Agarwal",
        "book_title": "Rajasthani Kitchen Secrets",
        "final_submission_date": "2024-09-30",
        "book_live_date": "2024-11-20",
        "royalty_status": "Paid – ₹21,600 on 2025-01-31",
        "isbn": "978-93-5741-205-2",
        "add_on_services": ["PR Campaign", "Bestseller Package", "Award Submission"],
        "whatsapp": "+91 9001122334",
        "instagram": "@sunitacooks",
        "dashboard_name": "Sunita Agarwal",
    },
    {
        "email": "vikram.iyer@gmail.com",
        "name": "Vikram Iyer",
        "book_title": "Code and Karma",
        "final_submission_date": "2025-02-10",
        "book_live_date": None,  # Not yet live
        "royalty_status": "N/A – Book not yet published",
        "isbn": "978-93-5741-206-9",
        "add_on_services": ["Editorial Review", "Author Copy x3"],
        "whatsapp": "+91 9845001234",
        "instagram": "@vikramiyertech",
        "dashboard_name": "Vikram I.",
    },
    {
        "email": "meera.pillai@gmail.com",
        "name": "Meera Pillai",
        "book_title": "Letters Never Sent",
        "final_submission_date": "2024-08-15",
        "book_live_date": "2024-10-01",
        "royalty_status": "Paid – ₹5,300 on 2024-12-31",
        "isbn": "978-93-5741-207-6",
        "add_on_services": ["Bestseller Package"],
        "whatsapp": "+91 9711223344",
        "instagram": "@meerapillai_writes",
        "dashboard_name": "Meera P.",
    },
    {
        "email": "aditya.bose@gmail.com",
        "name": "Aditya Bose",
        "book_title": "The Kolkata Chronicles",
        "final_submission_date": "2025-01-25",
        "book_live_date": "2025-04-15",
        "royalty_status": "Not Yet Due – Expected 2025-09-30",
        "isbn": "978-93-5741-208-3",
        "add_on_services": ["PR Campaign", "Award Submission"],
        "whatsapp": "+91 9433211234",
        "instagram": "@adityabosebooks",
        "dashboard_name": "Aditya Bose",
    },
    {
        "email": "fatima.khan@gmail.com",
        "name": "Fatima Khan",
        "book_title": "Shades of Lucknow",
        "final_submission_date": "2024-11-30",
        "book_live_date": "2025-01-25",
        "royalty_status": "Processing – Expected 2025-06-30",
        "isbn": "978-93-5741-209-0",
        "add_on_services": ["Editorial Review", "Bestseller Package"],
        "whatsapp": "+91 9654321098",
        "instagram": "@fatimakhanwrites",
        "dashboard_name": "Fatima K.",
    },
    {
        "email": "suresh.kumar@yahoo.co.in",
        "name": "Suresh Kumar",
        "book_title": "Villages I Never Left",
        "final_submission_date": "2024-07-01",
        "book_live_date": "2024-08-20",
        "royalty_status": "Paid – ₹3,200 on 2024-10-31",
        "isbn": "978-93-5741-210-6",
        "add_on_services": [],
        "whatsapp": "+91 9900112233",
        "instagram": "@sureshkumarauthor",
        "dashboard_name": "S. Kumar",
    },
]
